name: GitHub Script
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/workflows/bagivk56/ucad.team@main
        with:
          script: ssh ${{ secrets.USER }}@${{ secrets.ADDRESS }} "sh home/c73250/ucad.team.na4u.ru/app/deploy.sh"
